name: chasis
description: Orquestador de microfrontends en Flutter.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #  Manejo de rutas desacopladas
  go_router: ^14.8.1  

  #  Cliente HTTP
  dio: ^5.4.0
  http: ^1.3.0

  #  Manejo de variables de entorno
  flutter_dotenv: ^5.1.0

  #  Manejo de estado
  flutter_bloc: ^9.1.0
  provider: ^6.0.5

  #  Manejo de JSON
  json_annotation: ^4.8.1

  #  Almacenamiento seguro
  flutter_secure_storage: ^9.2.0
  shared_preferences: ^2.2.2

  #  Firebase
  firebase_auth: ^5.5.1
  firebase_auth_web: ^5.10.0
  firebase_core: ^3.12.1

  #  WebView
  webview_flutter: ^4.9.0
  webview_flutter_android: ^4.0.0
  webview_flutter_wkwebview: ^3.8.4

  #  Logs
  logger: ^2.0.2+1

  #  Inyecci贸n de dependencias
  get_it: ^8.0.3

  #  Comparaci贸n de estados
  equatable: ^2.0.5

  #  Info del dispositivo
  device_info_plus: ^11.3.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

  #  Generaci贸n de c贸digo para JSON
  build_runner: ^2.4.4
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/microfrontends.json
    - assets/.env
